### ISSUE TITLE
getAccountSells() is not working

### ISSUE THREAD

**Issue by fakhruddin50** [coinbase/coinbase-php#100]
I am using this method and facing this problem.
Fatal error: Call to undefined method Coinbase\Wallet\Client::getAccountSells()
so, why to send the BTC Coin.

**Comment by aianus** [comment]
You need to pass an account object to this method, as shown in the README:

```php
$account = $client->getPrimaryAccount(); // or some other account
$sells = $client->getAccountSells($account);
```
