### ISSUE TITLE
Enable to fetch  getAccountSells info

### ISSUE THREAD

**Issue by fakhruddin50** [coinbase/coinbase-php#101]
Hi Alex,
           I am using this method to get Sell Account Info. I am facing this problem.

```
       Error :- Fatal error: Call to undefined method Coinbase\Wallet\Client::getAccountSells();
      please send me any suggestion to solved this problem. 
```

$apiKey = 'aBDPgTawRPW01234';
$apiSecret = 'ASEDCGeGxmE6KZ8WtS8G7hHtYIncGjhii';
$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);
$account = $client->getPrimaryAccount(); 

$sells = $client->getAccountSells($account);

**Comment by aianus** [comment]
I suggest you revoke that API Key immediately

**Comment by magicsunday** [comment]
The documentation is outdated. There is no methode `getAccountSells` in the lib. Instead there is an "getSells" method.
