### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by iwex** [coinbase/coinbase-php#102]
Hello!

Could you please make it compatible with php7. 

Class name Resource is not allowed.

**Comment by luiz-brandao** [comment]
Not true, it's a `soft reserved word`. From the PHP manual:

> The following list of words have had soft reservations placed on them. Whilst they may still be used as class, interface, and trait names (as well as in namespaces), usage of them is highly discouraged since they may be used in future versions of PHP.

**Comment by sds** [comment]
Going to close as this appears to not be an issue. Feel free to open a new issue if you observe other problems with PHP 7 support. Thanks!
