### ISSUE TITLE
PHP Coinbase API not working on live but localhost

### ISSUE THREAD

**Issue by juvyc** [coinbase/coinbase-php#104]
I'm developing a system that will send BTC to a certain receiver via coinbase php api. The system is working fine in my localhost but after moving it to live it doesn't work and no error message. I tried tracing an error step by step by echoing the -3 and run the script and I found that when I put the echo after:

```
$account = $client->getPrimaryAccount();

echo -3;
```

..I've got a white page and no -3 as a test result.

Here's the full construction of this process:

```
$apiKey = "dfdsfsd";
$apiSecret = "fdsfdsfsfdff";

$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);
$_btc_wallet = @$_GET['_btcwallet'];
$_btc_amount = @$_GET['_btc_amount'];
$transaction = Transaction::send([
    'toBitcoinAddress' => $_btc_wallet,
    'bitcoinAmount' => $_btc_amount,
    'description' => 'Group Fund Transfer',
]);

$account = $client->getPrimaryAccount();

echo -3;

$client->createAccountTransaction($account, $transaction);
echo 1;
exit;
```

**Comment by Popkultur** [comment]
I have exactly the same issue here. However, I did not try it on local.

**Comment by onyijne** [comment]
Mine works fine both localhost and live, here is my code. 
`

    public function __construct() {
        $this->configuration = Configuration::apiKey($bitcoinApi, $bitcoinApiSecret);
        $this->client = Client::create($this->configuration);
        $this->client->enableActiveRecord();
        $this->account = $this->client->getAccount($bitcoinWallet);
    }

    public function sendBitcoin($toAddress, $amountInBTC, $description, $fee) {      
        $transaction = Transaction::send();
        $transaction->setToBitcoinAddress($toAddress);
        $transaction->setBitcoinAmount($amountInBTC);
        $transaction->setDescription($description);
        $transaction->setFee($fee);
        $this->client->createAccountTransaction($this->account, $transaction);
    }

     public function sendBitcoinToEmail($toEmailAddress, $amountInBTC, $description) {      
        $transaction = Transaction::send();
        $transaction->setToEmail($toEmailAddress);
        $transaction->setBitcoinAmount($amountInBTC);
        $transaction->setDescription($description);
        $this->client->createAccountTransaction($this->account, $transaction);
    }`

**Comment by Popkultur** [comment]
I found out what the issue was: Not correctly set permissions.
