### ISSUE TITLE
Argument 1 passed to Coinbase\Wallet\Exception\HttpException::exceptionClass()

### ISSUE THREAD

**Issue by tmbnh1** [coinbase/coinbase-php#106]
Hi everyone,
I use $client->createCheckout($checkout); and it show error 
_Argument 1 passed to Coinbase\Wallet\Exception\HttpException::exceptionClass() must be an instance of Psr\Http\Message\ResponseInterface, null given, called in /home/web/web/enigma.ymsolution.com/public_html/libs/coinbase_lib/vendor/coinbase/coinbase/src/Exception/HttpException.php on line 33 and defined in ...._

I check and see responer of error is null, I don't understand why error null the exception is called.

Please help me!
Thank you!

**Comment by rcoenen** [comment]
I am getting the same problem - no updates to this?

**Comment by sds** [comment]
Apologies for the lack of response here. I'm going to close this issue as it is quite old, but if you are able to provide a reproducible example in code feel free to reopen. Thanks!
