### ISSUE TITLE
Unable to get exchange rate from PLN to BTC (v1 API)

### ISSUE THREAD

**Issue by kafuwale** [coinbase/coinbase-php#112]
Fetching the exchange rates between PLN to BTC returns NULL

Function :   getExchangeRate('pln', 'btc'); returns as NULL

Checked coinse v1 API "GET https://api.coinbase.com/v1/currencies/exchange_rates" and not finding any entry for "pln_to_btc"

pln_to_btc was working fine before and now it stop working.

Can you please look into this ASAP

**Comment by sds** [comment]
Hey @kafuwale, thanks for the report.

As this is an issue with the API and not the client library itself, please contact our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-). Thanks!
