### ISSUE TITLE
How to request fresh accessToken for OAuth2 ?

### ISSUE THREAD

**Issue by mustaqim313** [coinbase/coinbase-php#113]
Could someone shows me how to use this v2 API for refreshing the accessToken?
TQ

**Comment by johnyi275** [comment]
https://developers.coinbase.com/docs/wallet/coinbase-connect/access-and-refresh-tokens

and though a little dated, a developer-written tutorial: 
https://community.coinbase.com/t/how-to-use-oauth-refresh-tokens-with-coinbase/1072
