### ISSUE TITLE
getExchangeRates() coinbase v2 API gives "invalid_scope" error

### ISSUE THREAD

**Issue by kafuwale** [coinbase/coinbase-php#114]
using getExchangeRates() function for coinbase v2 API gives exception saying "Scopes don't match current API version".

We have checked the API key and secret  key and permissions and seems to be fine.

Can you please look into this ASAP..

**Comment by jasonsavard** [comment]
I just got this recently also, I left the v2 permissions in tact and decided to remove the v1 scope/permissions in my Coinbase settings and the issue was resolved for me.

**Comment by kafuwale** [comment]
thanks @jasonsavard it works for me too after removing v1 scope/permissions .
Not sure it is expected behaviour from Coinbase API or not, I am still using V1 API for few stuff and now need to maintain two keys till we migrate to V2 :(
