### ISSUE TITLE
Basic account test always returns 401 Unauthorized / invalid signature

### ISSUE THREAD

**Issue by forwardtrends** [coinbase/coinbase-php#118]
Trying a basic test: 

require '../coinbase/vendor/autoload.php';

use Coinbase\Wallet\Client;
use Coinbase\Wallet\Configuration;

$apiKey = 'xxx';
$apiSecret = 'xxx';

$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);

$accounts = $client->getAccounts();

Always returns 401 Unauthorized / Invalid Signature. Yes, credentials are correct I've tried with 2 different account key / secret pairs. Any ideas what I'm doing wrong?

**Comment by samdoidge** [comment]
I am also getting this message currently.

**Comment by unr3al011** [comment]
Coinbase API will be activated after 48 hours. After that time it should work.

**Comment by benharold** [comment]
Closed with no resolution. What a joke.

**Comment by sds** [comment]
Hey @benharold, apologies if closing felt like no resolution was applied. I've been triaging issues and a response above suggested the issue would be solved if the user waited long enough, so I assumed the question was answered—incorrectly it seems.

Can you clarify what you are observing?

**Comment by benharold** [comment]
I observed essentially the same behavior as @forwardtrends posted.

I worked around the problem with a small python script.

Has the problem been solved in the PHP library?

**Comment by sds** [comment]
The reported issue does not appear to be related to this library in and of itself, but with the Coinbase API in general. For help with those issues, reach out to our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) to get assistance.
