### ISSUE TITLE
Return address after created

### ISSUE THREAD

**Issue by thienhaxanh2405** [coinbase/coinbase-php#121]
I think method createAccountAddress() in class Coinbase\Wallet\Client should change to
`return $this->postAndMap($account->getResourcePath().'/addresses', $data + $params, 'toAddress', $address);`
And then after create an address, we easily get string address
`$createAddress = $client->createAccountAddress($account, $addressParam);
var_dump($createAddress->getAddress());`

Any suggest for me.
Thanks.

**Comment by sds** [comment]
Thanks for the suggestion, @thienhaxanh2405.

This was implemented in #128 and is available as of version 2.6.0.
