### ISSUE TITLE
curl_reset() error

### ISSUE THREAD

**Issue by gaurav99t** [coinbase/coinbase-php#123]
why do i get this error?

 Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /home/therasd/public_html/coins/coinbase/coinbase-php-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 80

**Comment by sds** [comment]
Hey @gaurav99t, there's not much information to go on here. If you can provide an easily reproducible example we'd be happy to dig into this further, but going to close this issue for now. Thanks!
