### ISSUE TITLE
I can not setup payment tools. Can api payment work?

### ISSUE THREAD

**Issue by Comraovat** [coinbase/coinbase-php#125]
I am from VietNam, i can not setup payment tools. Can api payment work?

**Comment by sds** [comment]
Hey @Comraovat, please see the list of [countries](https://support.coinbase.com/customer/en/portal/articles/1392031-what-countries-are-buys-and-sells-available-in-) where buys/sells are available, or reach out to our [support](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) for more information. Thanks!
