### ISSUE TITLE
Cannot test API for two days

### ISSUE THREAD

**Issue by Inigovd** [coinbase/coinbase-php#129]
Hi,

As a developer, I have to wait 2 days for my API key to activate. That's 2 days of waiting to start developing. I don't see the option for a test-API key or the sandbox anymore. Is this correct?

Hope you could add a test API key which returns test data, for development.

Thank you

**Comment by RishabSwift** [comment]
We are talking about coinbase here. Coinsbase. No customer support. Has been going downhill lately. 
Removed a lot of API calls. We have started going with an alternative.

**Comment by sds** [comment]
Hey @Inigovd, I'm not able to reproduce this issue for new API keys. 

We do not offer a sandbox environment.

For actual customer support, please open a ticket with [support](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-). Thanks!
