### ISSUE TITLE
Recoverable fatal error: Argument 1 passed to Coinbase

### ISSUE THREAD

**Issue by Alex87311** [coinbase/coinbase-php#131]
Hello guys, I hope everything is going great for the team, Currently Im having an issue. Im making a checkflow payment with coinbase and I need to request an x amount of money and I thought I could use the example code to create a transaction  so the custumer could make a payment, but I'm facing this error. "Recoverable fatal error: Argument 1 passed to Coinbase\Wallet\Client::createAccountTransaction() must be an instance of Coinbase\Wallet\Resource\Account".

The createAccountTransaction Method is requesting me an account, so why in your example  code is not being used, Im not sure if the client needs an account on coinbase or he can have a wallet from another company , I think, I created a new one with the following function. 
 $toAccount = new Account([
      'name' => 'costumeremail@email.com'
    ]);

But when I try this method, it gives me the following error message " Coinbase\Wallet\Exception\NotFoundException: Client error: `POST https://api.coinbase.com/transactions` resulted in a `404 Not Found` response: <!DOCTYPE html> <html xmlns:fb="http://ogp.me/ns/fb#"> <head> <title>Coinbase &mdash; 404 Not Found</title> <meta charse (truncated...) in Coinbase\Wallet\Exception\HttpException::wrap() (line 37 of /var/www/html/project/vendor/coinbase/coinbase/src/Exception/HttpException.php)."

Just to make sure, I did all the steps to request funds, but Im not sure what Im missing, I would greatly apreciate if you guys can share additional information or code if need it. 

Thank you for all the help and support.

**Comment by sds** [comment]
Hey @Alex87311, it's a bit difficult to deduce from the details you've provided what's going wrong, but it may simply be an incorrect use of the client library API. The first issue appears to be a documentation issue, but we would appreciate you linking us to the documentation where you read that the first argument was not an `Account` instance? Thanks!

**Comment by sds** [comment]
Closing due to lack of response. Feel free to open a new issue with a set of reproducible steps, or feel free to get in contact with our [support team](https://support.coinbase.com/). Thanks!
