### ISSUE TITLE
Cannot create send bitcoin to bitcoin address

### ISSUE THREAD

**Issue by hoangsonx** [coinbase/coinbase-php#132]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.coinbase.com/v2/accounts/f7ad7563-7778-............/transactions` resulted in a `422 Unprocessable Entity` response: {"errors":[{"id":"validation_error","message":"To financial institution can't be blank"}],"user_warnings":[{"id":"extra_ (truncated...) ' in /var/www/html/includes/coinbase/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/html/includes/coinbase/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/html/includes/coinbase/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/includes/coinbase/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/html in /var/www/html/includes/coinbase/vendor/coinbase/coinbase/src/Exception/HttpException.php on line 37

**Comment by PriyanshDwivedi** [comment]
same issue here.
And this happens on some particular amounts like 0.254, 0.355 or something. No clue what's the issue. 
Any help guys?

**Comment by dongido001** [comment]
same here, any solution to this?

**Comment by PriyanshDwivedi** [comment]
Any response from @johnnycoinbase @dai-cb @warrentagle-coinbase-com ??
I have followed the exact example for send transaction as shown in readme file but still getting above posted error on some specific bitcoin amounts.
Need to resolve this issue really fast as this is affecting our business. Any help would be appreciated..

**Comment by PriyanshDwivedi** [comment]
@hoangsonx Did you find any solution yet?

**Comment by sds** [comment]
Hey @hoangsonx, since this issue might require information specific to your account in order to debug, and isn't specific to the client library itself, please reach out to our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) for assistance. Thanks!
