### ISSUE TITLE
composer update issue.

### ISSUE THREAD

**Issue by riyaz1989** [coinbase/coinbase-php#135]
Hi Team,

Horrible!!!!! Whenever I am trying to run `composer require coinbase/coinbase` or by putting `"coinbase/coinbase": "~2.0"` it showing follwing error. please check screenshot. 

Thanks in advance. 

![image](https://user-images.githubusercontent.com/26436818/33699124-3092ff50-db37-11e7-8c95-d89aba121d50.png)

**Comment by sds** [comment]
I'm unable to reproduce.

```
⨠ composer require coinbase/coinbase
Using version ^2.5 for coinbase/coinbase
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing coinbase/coinbase (2.5.0): Downloading (100%)
Writing lock file
Generating autoload files
```

I'm going to close as this is likely an issue with a local development environment. Feel free to open a new issue if you can provide a set of steps to reliably reproduce. Thanks!
