### ISSUE TITLE
Fatal error: Class 'Coinbase\Wallet\Configuration' not found in C:\xampp\htdocs\coinbase2\index.php on line 10

### ISSUE THREAD

**Issue by Govind13100** [coinbase/coinbase-php#136]
I just clone your library , ran ' composer update ' and made a index.php file with code 
````
use Coinbase\Wallet\Client;
use Coinbase\Wallet\Configuration;


$apiKey    = '*********';
$apiSecret = '*********';

$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);
print_r($client);
````

giving this error

**Fatal error: Class 'Coinbase\Wallet\Configuration' not found in C:\xampp\htdocs\coinbase2\index.php on line 10**

I don't know why?? Can any one suggest , I am newbie to github

**Comment by bulgariamitko** [comment]
did you use composer to install the project or did you used github clone function? how did u get the lib to your com?

**Comment by Govind13100** [comment]
I solved this issue by my self already , the autoload was missing to include. In doc there is no mention of this.

**Comment by DevMachineAlpha** [comment]
Govind13100, can you explicitly tell me how you fixed this? I am getting the same error and the documentation is very poor.

**Comment by shaharia-itglobal** [comment]
Can you plz share the answer ??

**Comment by nextpulse** [comment]
Add something similar to this in your code (before the 'use Coinbase\...'): 

require_once('vendor/autoload.php');  _//change the file path accordingly to your dir_
