### ISSUE TITLE
Creation of multiple BTC accounts is not supported

### ISSUE THREAD

**Issue by pktejani** [coinbase/coinbase-php#142]
[29-Dec-2017 06:28:18 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.coinbase.com/v2/accounts` resulted in a `400 Bad Request` response:
{"errors":[{"id":"invalid_request","message":"Creation of multiple BTC accounts is not supported"}]}

**Comment by victor-suriel** [comment]
I had this same problem with the Python API, so I think that they disabled this feature.

**Comment by Govind13100** [comment]
I face the same problem , is there any solution yet ???

**Comment by idoor88** [comment]
Any solutions for this issue, I got the same error message when I am trying to create a new account as this:
`$account = new Account([
    'name' => 'New Account'
]);
$client->createAccount($account);`

Thanks
IDooor

**Comment by sds** [comment]
Hey @pktejani, as was already mentioned we don't support creation of multiple BTC accounts.

**Comment by ksharonov** [comment]
Hello. Any information about problem?
