### ISSUE TITLE
Send from one wallet to another is not working

### ISSUE THREAD

**Issue by wuanhu88** [coinbase/coinbase-php#147]
I created account with my apikey and created 4 wallets, I am trying to send fund from one wallet to another of my own wallets, but I got "To financial institution can't be blank" error, not sure what that means, here is my php code:

$transaction = Transaction::send();

$transaction->setToBitcoinAddress('1PnVQFQ4j6o6eLExBUS36nqbszMHppydoH');
$transaction->setBitcoinAmount(1);
$transaction->setDescription('For being awesome!');
$transaction->setFee('0.0001');`
$client->createAccountTransaction($account, $transaction);

also when I used my an email address to create the send transaction, I got "You don't have that much" error, is this talking about fund balance of my account? I have not put any funds in my account yet, but I like to test coinbase api with my account, does that mean I have to put real money in my account for testing?

So please help me with the these two errors, thanks very much!

WH

**Comment by sds** [comment]
Hey @wuanhu88, you need to have funds in your account in order to send them in a transaction.

We do not have a sandbox environment at this time.
