### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by Govind13100** [coinbase/coinbase-php#148]
I want to use this API to generate BCH wallet , send BCH from one to another address and get transaction details.

Is there any sandbox or testnet server associate with it ????

If there something else please suggest me..

Thanks in advance.

**Comment by sds** [comment]
There is no sandbox functionality at this time.

**Comment by csimpi** [comment]
Still not possible to test?

**Comment by sds** [comment]
No, there is no sandbox at this time, and no plans to support one in the near term.
