### ISSUE TITLE
Feature Request: optional parameter for arbitrary data submitted with OAuth authorizeUrl

### ISSUE THREAD

**Issue by tim-peterson** [coinbase/coinbase-php#15]
Feature Request: It'd be nice to be able to submit optional data in the OAuth authorizeUrl query string. 

I apologize is this is possible but I haven't succeeded doing this with this library as it is.

**Comment by aianus** [comment]
We no longer provide OAuth handshake functionality in the library. You can handle the handshake process using an [OAuth2 client](https://packagist.org/search/?q=oauth2%20client) such as [league/oauth2-client](https://packagist.org/packages/league/oauth2-client).
