### ISSUE TITLE
Can't create BCH new wallet

### ISSUE THREAD

**Issue by Govind13100** [coinbase/coinbase-php#150]
` `400 Bad Request` response: {"errors":[{"id":"invalid_request","message":"Creation of multiple BTC accounts is not supported"}]} '`

how to overcome this error ??

**Comment by idoor88** [comment]
I got the same problem when I followed the example:

`$account = new Account([
    'name' => 'New Account'
]);
$client->createAccount($account);`

Anybody there has a solution? desperately waiting for answer.

Thanks
idoor

**Comment by sds** [comment]
Please try out the latest package version (2.7.0 at time of writing) and open a new issue if this is still a problem. Thanks!
