### ISSUE TITLE
Creating new address will return last address from wallet

### ISSUE THREAD

**Issue by an4rei** [coinbase/coinbase-php#151]
Hello! 

Everything was working okay until last night.

I have about 2000 addresses with unique names and now when I'm trying to create a new address , I get returned the last created address from my wallet(I can manually create addresses from coinbase dashboard) but seems like API won't work.

Any other API functions work correctly so far from what I tested.

**Comment by virms77** [comment]
Hello!
Same issue.

**Comment by an4rei** [comment]
Good to know I'm not the single one experiencing this issue. Seems like the address generating works only once in a while . I have like 10 duplicated addresses and then another 12 duplicated(different from the first ones). Also , sometimes BTC address generation works but ETH address generation doesn't and so on.

It's a very weird behaviour.

**Comment by Cloud-Man** [comment]
I have the same issue too.

**Comment by ctubio** [comment]
everybody have same issue today https://github.com/coinbase/coinbase-node/issues/119

**Comment by sagirba** [comment]
Yes, I have the same issue too. Its very bad :( fix this please

**Comment by BlackSnow98** [comment]
Same here. FIX PLS!!!!!!!!!!!!!

**Comment by usar-naem** [comment]
+1, losing a lot of money every hour.

**Comment by PriyanshDwivedi** [comment]
guys, any fix?? this is really bad.. :(

**Comment by sagirba** [comment]
Guys, please write to support https://support.coinbase.com/ with link to this issue!
Let's try to speed up the response of the developers!

**Comment by an4rei** [comment]
Calling them is better , you can free call them on Skype from any country on : +1 (888) 908-7930

**Comment by ctubio** [comment]
![530-walkie-talkie](https://user-images.githubusercontent.com/1634027/35389428-f96ec7bc-01d7-11e8-8171-07d77df9ca34.jpg)

**Comment by PriyanshDwivedi** [comment]
any updates??

**Comment by HanseCurie** [comment]
Very sad... new addresses on btc and eth no longer are created.
Please fix this issue quickly..
we have been losing a lot of money and customers.

**Comment by ctubio** [comment]
by now should be fixed

**Comment by PriyanshDwivedi** [comment]
confirmed. Working fine now.

**Comment by BlackSnow98** [comment]
sorry for spam, but can someone tell how i can get network fee in coinbase via API?

**Comment by sds** [comment]
Closing as this has been reported as fixed.
