### ISSUE TITLE
The Coinbase API only accepts transactions to an account, email, or bitcoin address

### ISSUE THREAD

**Issue by hakerkiler** [coinbase/coinbase-php#156]
On use your API i get this error mesage? How to resolve this problem?

**Comment by PriyanshDwivedi** [comment]
Are you trying to send BTC? 
Please share how you've set the 'to' field so that someone can help.

**Comment by sds** [comment]
Hey @hakerkiler, sounds like an invalid address, but more information is required. Also please make sure you are using the latest package version ([2.7.0](https://github.com/coinbase/coinbase-php/releases/tag/2.7.0) at time of writing).
