### ISSUE TITLE
Not enough funds exception

### ISSUE THREAD

**Issue by StefanYohansson** [coinbase/coinbase-php#157]
Hi,

I am using `Transaction::send` function to send funds from Coinbase to another wallet

```php
$transaction = Transaction::send([
    'toBitcoinAddress' => $address,
    'amount'           => new Money($amount, CurrencyCode::BTC),
    'description'      => 'Payment ' . date('Y-m-d H:i:s'),
]);
$this->coinbase->action('createAccountTransaction', [$account, $transaction]);
```
but I am receiving:

```
BadRequestException in HttpException.php line 37: You don’t have enough funds in this account for this transaction. Please try again with a smaller amount.

at HttpClient->send(object(Request), array('type' => 'send', 'amount' => '0.00330258', 'description' => 'Payment 2018-02-07 09:38:45', 'to' => '1qohAr4uxKWyCDrGYrjNvoFLEpbRGnAtL', 'currency' => 'BTC')) in HttpClient.php line 121
```

I have exactly '0.00330258' on my account. how should I know the minimum or how much should I subtract to make it work? should I consider the fee? Should the fee be calculated automatically and decreased from the amount?

**Comment by sds** [comment]
Hey @StefanYohansson, transaction fees should be obtainable from the network as of #138, which you need to factor in to the cost. Hope that helps.

**Comment by StefanYohansson** [comment]
@sds thanks for pointing me out to that solution, but I have few questions about #138 

```
return new Network($value['status'], isset($value['hash']) ? $value['hash'] : null, isset($value['transaction_fee']) ? $value['transaction_fee'] : null);
```

this line is declared on `src/Mapper.php` but I don't know how to use it or if I should use it directly. Can you provide me an example of how to correctly request this data? I can't find anything related to this on API documentation.

**Comment by sds** [comment]
Apologies @StefanYohansson, I misunderstood what was going on in that PR. 

We don't currently offer a way to obtain a network fee estimate through the public API. Would recommend you either:
* Maintain an extra buffer of funds in your account for the automated fee
* Specify the fee yourself (note if this is too low it could result in the transaction never confirming, which is why this is not recommended)

Hope that helps.
