### ISSUE TITLE
API v2 - Merchant flow is possible?

### ISSUE THREAD

**Issue by luisbatista** [coinbase/coinbase-php#158]
Hello,

I start Coinbase API, I saw the API v2, but if have a few questions to validate if I can made what I want to my website.
The idea is to sell virtual products to registered customers, with criptocurrency. The customer, in their profile, can enter the bitcoin address (or ethereum address). Sometimes the website reward customers and send bitcoins (or ethereum) to their cripto wallet.

With Coinbase API I can:
1) create a button / action to make a purchase? (what I need to use: create Checkout, create Order). We can show a button where the user press and is showed the Coinbase interface to make the playment.
2) send from merchant bitcoin address (or ethereum address) to user, in backend, without human action ? (what need to use)

I saw the Coinbase Merchant, but only have a "button wizard", can't programmatic make my settings and obtain the code (or html) to use.

Or is better use the "old" API v1 to make this flow ?

Best Regards,
LB

**Comment by sds** [comment]
Hey @luisbatista, we'd like to keep this space for questions related to the `coinbase-php` project itself (issues with the code, feature suggestions, etc.)

However, would recommend you check out https://commerce.coinbase.com for an easy way to build a purchase flow. Thanks!
