### ISSUE TITLE
The transaction fee has expired

### ISSUE THREAD

**Issue by AlexKirsanoff** [coinbase/coinbase-php#163]
I have error "The transaction fee has expired" on all transactions with fee parameter (Client.createAccountTransaction method)

**Comment by sds** [comment]
Hey @AlexKirsanoff, as this is an API issue and not an issue with this project itself, can you open a ticket with our [support team](https://support.coinbase.com) so they can have a look? They'll have access and insight that developers on this project won't have. Thanks!
