### ISSUE TITLE
API for create ETH wallet/address

### ISSUE THREAD

**Issue by gunjanbacancy** [coinbase/coinbase-php#165]
Hi,
How can I create ETH wallet/address using API ?
Thanks in advance.

**Comment by sds** [comment]
Hey @gunjanbacancy, as was mentioned by @tummybos, while signed in to your account you can go to https://www.coinbase.com/accounts and click on your Ethereum wallet to see your account ID appear in the URL bar. You can then use that as your account ID.

**Comment by Benjamin0000** [comment]
how do i send ethereum, litecoin, bitcoin cash, etc  with this same api. in bitcoin it is   
`$transaction = Transaction::send([
        'toBitcoinAddress' => $order->address,
        'amount'           => new Money($amount, CurrencyCode::USD),
        'description'      => 'Bitcoin from Pimaxchange.com'
        // 'fee'              => '0.0001' // only required for transactions under BTC0.0001
      ]);`
what should i change the 'toBitcoinAddress' to for every other ones.

**Comment by raisex** [comment]
@sds sorry but we donì't understund why other address via api are not generated with error account id. We have generated only btc, when we add account id eth, we have account not found. How we can solve it ?
