### ISSUE TITLE
Cant send more than $3000

### ISSUE THREAD

**Issue by tummybos** [coinbase/coinbase-php#166]
I can't figure out how to send more than $3000.
It returns an error `To financial institution can't be blank`
I cant figure out how to specify `to_financial_institution` and `financial_institution_website` using the php client.
**I did this code and it does not work:**```

	$transaction = Coinbase\Wallet\Resource\Transaction::send(array(
		'to' => $to,
		'amount'           => new Coinbase\Wallet\Value\Money($request->get('amount'), $symbol),
		'description'      => 'Withdrawal',
		//'fee'              => '0.0001', // only required for transactions under BTC0.0001
		'idem' =>$idem,
		'to_financial_institution' => true,
		'financial_institution_website' => 'example.com',
	));
```
Also the `idem` seemed not to be set on the transaction.
This is really frustrating.
Please how can I get pass the issue?

**Comment by sds** [comment]
Hey @tummybos, as your issue sounds specific to your account and not due to this library, please open a ticket with our [support team](https://support.coinbase.com) who have the necessary access to look into your situation.

Thanks!
