### ISSUE TITLE
How many address create under account ?

### ISSUE THREAD

**Issue by gunjanbacancy** [coinbase/coinbase-php#168]
Hi,
How many address create under single account ?
e.g. I have Bitcoin account then how many address create under Bitcoin account ? (using coinbase API)

Thanks in advance

**Comment by sds** [comment]
Hey @gunjanbacancy, we impose rate limits on how many addresses you can create during a given interval of time, but there is no limit on the total number of addresses. However, obvious abuse of our systems is in violation of our [Terms of Service](https://www.coinbase.com/legal/user_agreement?locale=en-US), so please be sensible. 

Hope this helps!
