### ISSUE TITLE
Coinbase don't provide API secret

### ISSUE THREAD

**Issue by esqui2002** [coinbase/coinbase-php#171]
Coinbase only show API key. I need secret key

**Comment by gustavorglima** [comment]
Secret Key show when you request New API Key.

**Comment by esqui2002** [comment]
Yes, but only show API key

**Comment by sds** [comment]
Hey @esqui2002, 

Go to https://www.coinbase.com/settings/api, click **New API Key**. Fill out the scopes you want to assign the key.

You'll then see a dialog displaying the API key and secret:

<img width="555" alt="screen_shot_2018-04-24_at_1_54_57_pm" src="https://user-images.githubusercontent.com/677877/39213770-4e01a94a-47c7-11e8-9fb2-c78cc92967e9.png">

For security reasons, you only get to see this **once**, so make sure you copy it to a safe place. Hope that helps!

**Comment by Droppix** [comment]
Hi,

I did exactly the same thing, except that the secret key is not displayed (after activating it).
Suggestion?

Thanks

**Comment by Droppix** [comment]
Ok, I found but work only on **Safari** and  **not Chrome**.
