### ISSUE TITLE
after install from composer

### ISSUE THREAD

**Issue by shubhamkhuva** [coinbase/coinbase-php#175]
i install from composer and this code need meybe  Coinbase\Wallet\Resource;
wallet folder but i did'nt see i got error page not working in 
<?php
	use Coinbase\Wallet\Client;
	use Coinbase\Wallet\Configuration;

	$configuration = Configuration::apiKey($apiKey, $apiSecret);
	$client = Client::create($configuration);
?>

**Comment by sds** [comment]
Hey @shubhamkhuva, I'm not sure I understand what issue you are encountering. Can you post a list of reproducible steps with code so we can understand the problem?
