### ISSUE TITLE
can't send money

### ISSUE THREAD

**Issue by nbhooi** [coinbase/coinbase-php#177]
get validation error when sending money. i got sufficient fund but get the error below.
 Coinbase\Wallet\Value\Error::__set_state(array(
       'id' => 'validation_error',
       'message' => 'To financial institution can\'t be blank',
       'url' => NULL,
    ))

**Comment by sds** [comment]
Hey @nbhooi, as your issue sounds specific to your account and not due to this library, please open a ticket with our [support team](https://support.coinbase.com) who have the necessary access to look into your situation.

Thanks!
