### ISSUE TITLE
Litecoin transaction error

### ISSUE THREAD

**Issue by KAMAELUA** [coinbase/coinbase-php#179]
https://github.com/coinbase/coinbase-php/blob/7443d2c98ab10f3fcba92005790291484bd566be/src/Mapper.php#L123-L127

It refers that Coinbase API only accepts transactions to an account, email, or bitcoin address, but in official documentation says that it accepts a bitcoin address, bitcoin cash address, litecoin address, ethereum address, or an email of the recipient.

https://developers.coinbase.com/api/v2#send-money

![image](https://user-images.githubusercontent.com/3611515/43049987-f95dc246-8e09-11e8-911a-71858d38967d.png)

**Comment by sds** [comment]
Thanks for pointing this out, @KAMAELUA. Would love a PR that corrects this logic detection!

**Comment by KAMAELUA** [comment]
@sds you are welcome #180.

**Comment by sds** [comment]
Fixed in #180. Thank you!
