### ISSUE TITLE
The transaction "description" field

### ISSUE THREAD

**Issue by YasserNoureldin** [coinbase/coinbase-php#183]
Hallo,

I have a question that regarding the transactions, Is the description field stored somewhere in the transaction outputs or scripts or its only some description from coinbase website and it has nothing to do with the transaction?

Also is there a way using the API to add an OP_RETURN output with custom data from me?

Thanks.

**Comment by Hackinet** [comment]
Yes, the description field is stored. You can pass your custom information in description and fetch it later. However, you can't add pass custom information directly while creating a Coinbase transaction.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
