### ISSUE TITLE
Add the official API "Get 24hr Stats" with daily open-high-low-volume stats

### ISSUE THREAD

**Issue by maxvergelli** [coinbase/coinbase-php#185]
I didn't find any method for the "Get 24hr Stats" API  in the Market Data, does it exists?

Here is the reference of the official API:
https://docs.prime.coinbase.com/#get-24hr-stats

{
    "open": "34.19000000",
    "high": "95.70000000",
    "low": "7.06000000",
    "volume": "2.41000000"
}

Get 24 hr stats for the product. volume is in base currency units. open, high, low are in quote currency units.
HTTP request

GET /products/<product-id>/stats

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
