### ISSUE TITLE
i want to send ethereum and other asset supported by coinbase.

### ISSUE THREAD

**Issue by Benjamin0000** [coinbase/coinbase-php#187]
how do i send ethereum, litecoin, bitcoin cash, etc with this same api. in bitcoin it is
`$transaction = Transaction::send([ 'toBitcoinAddress' => $order->address, 'amount' => new Money($amount, CurrencyCode::USD), 'description' => 'Bitcoin from' // 'fee' => '0.0001' // only required for transactions under BTC0.0001 ])`;
what should i change the 'toBitcoinAddress' to for every other ones.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
