### ISSUE TITLE
More Information on how to set up webhook

### ISSUE THREAD

**Issue by bumbumpaw07** [coinbase/coinbase-php#189]
I already added notification url on my setting. But documentation does not tell how to use this url.

What to add on this url, is this one 

```
$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);
$raw_body = file_get_contents('php://input');
$signature = $_SERVER['HTTP_CB_SIGNATURE'];
$authenticity = $client->verifyCallback($raw_body, $signature); // boolean

```

How will i know that there is a transfered payment to one of my generated address under my account?

**Comment by sahidul99** [comment]
Have you got solution? And what is  HTTP_CB_SIGNATURE?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
