### ISSUE TITLE
Request Fund process not working

### ISSUE THREAD

**Issue by zubaer93** [coinbase/coinbase-php#191]
When I request for fund error shows like 
 **"Message: Argument 1 passed to Coinbase\Wallet\Client::createAccountTransaction() must be an instance of Coinbase\Wallet\Resource\Account, instance of Coinbase\Wallet\Resource\Transaction given, called in D:\wamp\www\open_digy-pay\trunk\application\modules\web_service\controllers\web_service.php on line 144 and defined"**

So when I add account instance with it  ($client->createAccountTransaction($account, $transaction);) the following error shows
**"Required parameter missing: to"**

after that when I try to add "to" on transaction like this

 $transaction = Transaction::request([
            'amount'      => new Money(8, CurrencyCode::USD),
            'description' => 'For test',
            'to' => "test@test.com"
        ]);

the following error shows

**Argument 1 passed to Coinbase\Wallet\Resource\Transaction::setTo() must be an instance of Coinbase\Wallet\Resource\Resource, string given, called in C:\xampp\htdocs\colt_api\vendor\coinbase\coinbase\src\Resource\Resource.php on line 70**

PLEASE HELP

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
