### ISSUE TITLE
v1 API operational?

### ISSUE THREAD

**Issue by Crypto2** [coinbase/coinbase-php#193]
Is the v1 API still operational? We're one of the oldest integrations with Coinbase so still using it because our users would have to re-link if we switch to v2.

We're getting 404 errors while trying to use it, ie. https://api.coinbase.com/v1/accounts

**Comment by sds** [comment]
Hey @Crypto2, API v1 was shut down. You'll need to migrate to V2.

**Comment by Crypto2** [comment]
What happened to it? I didn't see any announcements it was being shut down and all the docs are still up and the API keys page still has v1 permissions.

**Comment by dionvaladez** [comment]
Let me see where you were shot down and let me see what I could do for your account and I will email you back
________________________________

**Comment by Crypto2** [comment]
We've already updated to v2 now, had to announce to everyone and make them link with a new key. Just expect better from Coinbase than to shut something down with no notice.

**Comment by dionvaladez** [comment]
Okay
________________________________
