### ISSUE TITLE
Transaction ID is empty coinbase api php

### ISSUE THREAD

**Issue by alfredogt** [coinbase/coinbase-php#197]
I am trying to send money from my account in CoinBase to a Bitcoin hash using the PHP library. This is my code:

```
$configuration = Configuration::apiKey($k1,$k2);
$client = Client::create($configuration);
$account = $client->getPrimaryAccount();
$transaction = Transaction::send([
            'toBitcoinAddress' => 'asdasdasdasd',
            'amount'           => new Money(0.5, CurrencyCode::USD),
            'description'      => 'Descripcion',
        ]);
$client->createAccountTransaction($account, $transaction); // return void

print_r($transaction->getNetwork()->getStatus()); // is "Pending"
print_r($transaction->getNetwork()->getHash()) // is empity
```
I need to know when the transaction was sent correctly.
I need to know how many verifications the transaction has
The money is sent correctly, but I do not know how to obtain the ID of that transaction.

Does anyone have a solution? Thank you!

**Comment by Hackinet** [comment]
You can get the transaction Resource ID with `$transaction->getRawData()["id"];`
