### ISSUE TITLE
Help Buying other Coins

### ISSUE THREAD

**Issue by MrDevBC** [coinbase/coinbase-php#198]
I've been trying to figure this for hrs.

Here is my code:

`
$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);  

$accounts = $client->getAccounts();
$account = $client->getPrimaryAccount(); // or some other account

$buy = new Buy([
'amount' => new Money(5.5, 'ETH'),
'currency' => 'ETH',
]);

// even try this too:
$buy = new Buy([
'amount' => new Money(5.5, CurrencyCode::ETH),
'currency' => CurrencyCode::ETH,
]);

$client->createAccountBuy($account, $buy, [Param::COMMIT => false]);
//$selldetail = $client->commitSell($sell);

$PaymentDetail = $client->decodeLastResponse();
//$PaymentArray =  $PaymentDetail['data'];

echo '<pre>';
print_r($PaymentDetail);
echo '</pre>';
`

It's throwing me this error:
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.coinbase.com/v2/accounts/{account-id}/buys` resulted in a `400 Bad Request` response: {"errors":[{"id":"invalid_request","message":"Amount must be specified in either source or target currency"}]} 

if you could help me

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
