### ISSUE TITLE
getting error "Fatal error: Interface 'Coinbase\Wallet\Authentication\Authentication' not found in /home/[MY_DIRECTORIES]/src/Authentication/ApiKeyAuthentication.php on line 8"

### ISSUE THREAD

**Issue by sahidul99** [coinbase/coinbase-php#200]
I am trying to test coinbase api ,I have downloaded library from github and create a index as bellow
```
<?php
 require_once('src/Client.php');
 require_once('src/Configuration.php');
 require_once('src/Authentication/ApiKeyAuthentication.php');
use Coinbase\Wallet\Client;
use Coinbase\Wallet\Configuration;

$apiKey="";
$apiSecretp="";

$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);

?>


```

and I am receving bellow error

`Fatal error: Interface 'Coinbase\Wallet\Authentication\Authentication' not found in /home/exhakduz/api/coinbase-php-master/src/Authentication/ApiKeyAuthentication.php on line 8`

**Comment by ghost** [comment]
You might just need to require_once 'autoload.php' from the vendor folder, instead of these lines:
require_once('src/Client.php');
require_once('src/Configuration.php');
require_once('src/Authentication/ApiKeyAuthentication.php');

**Comment by sahidul99** [comment]
Thanks for the reply, when I downloaded and host it directly there was no vendor/autolad.php file and thats why using require once 'autolad.php' genarete error. But now problem is solved already when I used composer command to download library.
