### ISSUE TITLE
Most functions are returning empty array   

### ISSUE THREAD

**Issue by sahidul99** [coinbase/coinbase-php#202]
I am trying to test coinbase api. Api authorized fine but most functions are returning empty arrey, bellow is my code sample

 

    <?php
    require_once('vendor/autoload.php');
    use Coinbase\Wallet\Resource\Account;
    use Coinbase\Wallet\Client;
    use Coinbase\Wallet\Configuration;
    use Coinbase\Wallet\Enum\CurrencyCode;
    use Coinbase\Wallet\Resource\Transaction;
    use Coinbase\Wallet\Value\Money;
    use Coinbase\Wallet\Resource\Address;
    
    $apiKey='********';
    $apiSecret='********;';
    
    $configuration = Configuration::apiKey($apiKey, $apiSecret);
    $client = Client::create($configuration);
    
    $accounts = $client->getAccounts();
    $account = $client->getPrimaryAccount();
    $auth = $client->getCurrentAuthorization();
    $user = $client->getCurrentUser();
    $paymentMethods = $client->getPaymentMethods();
    
    echo "accounts arrey". json_encode($accounts)."<hr/>";//empty arrey
    echo "primary account arrey".json_encode($account)." <hr/>";//empty arrey
    echo "current auth arrey".json_encode($auth)."<hr/>";//printing data perfectly
    echo "current user arrey".json_encode($user)."<hr/>";//empty array 
    echo "payment methods arrey".json_encode($paymentMethods)."<hr/>";//empty array 
     
    
    ?>   

All of echo printing empty array except `$auth`bellow is output screenshot

[![output screenshot][1]][1]

  [1]: https://i.stack.imgur.com/rcTUS.jpg

**Comment by teaguehannam** [comment]
I have been using "$data = $client->decodeLastResponse();" to get the request data. This skips any need for json encoding.
$client->getAccounts();
$account = $client->getPrimaryAccount();
$auth = $client->getCurrentAuthorization();
$user = $client->getCurrentUser();
$paymentMethods = $client->getPaymentMethods();

**Comment by ghost** [comment]
I've been using this line, "$data = $client->decodeLastResponse();" to decode the data. This way you don't have to use JSON.

For example:
$client->getAccounts();
$accounts = $client->decodeLastResponse();

**Comment by sahidul99** [comment]
@teaguehannam yes it works this way.tnx a lot

**Comment by sahidul99** [comment]
@teaguehannam for me this is working when using json_encode function like bellow
```
$client->getAccounts();
$accounts = $client->decodeLastResponse();
echo json_encode($accounts);

```

if use echo directly from `decodeLastResponse()` then same error could not be convarted to string

**Comment by ghost** [comment]
I don't think you need to json_encode it, the $accounts is returned as an array. I have a function that displays arrays to be easily readable, but "print_r($accounts);" should show the data you recieved.

But that's as far as I am, I am not sure how work a request like this:

$transactions = $client->getAccountTransactions($account);

The $account needs to assigned as an instance in order to work.
