### ISSUE TITLE
What is $_SERVER['HTTP_CB_SIGNATURE'] in coinbase api notification?

### ISSUE THREAD

**Issue by sahidul99** [coinbase/coinbase-php#203]
Hi I am trying to use coinbase api,api implementation is Working fine but facing problem on notification. Accroding to documentation I have created Notification url and codes are bellow

    <?php
       require_once('vendor/autoload.php');
    
    use Coinbase\Wallet\Client;
    use Coinbase\Wallet\Configuration;
    
    
    $apiKey=" xxxx";
    $apiSecret="xxxx";
    
    
    
    $configuration = Configuration::apiKey($apiKey, $apiSecret);
    $client = Client::create($configuration);
    
    $raw_body = file_get_contents('php://input');
    $signature = $_SERVER['HTTP_CB_SIGNATURE'];
    $authenticity = $client->verifyCallback($raw_body, $signature); // boolean
    if($authenticity){
     $data = json_decode($raw_body, true);
        mail("sahid4745@gmail.com","Coinbase Payment Notifications",print_r($order, true));
    }
    $message=$raw_body;
    mail('sahid4745@gmail.com', 'My Subject', $message);
    
    
    
    ?>    

But this is producing error as  Notice: 

> Undefined index: HTTP_CB_SIGNATURE in /home/exhakduz/api/webhooks.php
> on line 38

I Don't know actually what is server_cb_signature, if some one can explain that will be great help for me.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
