### ISSUE TITLE
Help with USDC

### ISSUE THREAD

**Issue by chidang** [coinbase/coinbase-php#204]
Got error when check Transaction info of USDC
==============
local.ERROR: Unrecognized resource type: usd_coin_network {"exception":"[object] (Coinbase\\Wallet\\Exception\\RuntimeException(code: 0): Unrecognized resource type: usd_coin_network at /var/www/project/myproject/vendor/coinbase/coinbase/src/Mapper.php:841)
[stacktrace]
#0 /var/www/project/myproject/vendor/coinbase/coinbase/src/Mapper.php(658): Coinbase\\Wallet\\Mapper->createResource('usd_coin_networ...', Array)
#1 /var/www/project/myproject/vendor/coinbase/coinbase/src/Mapper.php(591): Coinbase\\Wallet\\Mapper->toPhp('from', Array)
#2 /var/www/project/myproject/vendor/coinbase/coinbase/src/Mapper.php(534): Coinbase\\Wallet\\Mapper->injectResource(Array, Object(Coinbase\\Wallet\\Resource\\Transaction))
#3 /var/www/project/myproject/vendor/coinbase/coinbase/src/Mapper.php(118): Coinbase\\Wallet\\Mapper->injectTransaction(Array, NULL)
#4 /var/www/project/myproject/vendor/coinbase/coinbase/src/Client.php(850): Coinbase\\Wallet\\Mapper->toTransaction(Object(GuzzleHttp\\Psr7\\Response), NULL)
#5 /var/www/project/myproject/vendor/coinbase/coinbase/src/Client.php(342): Coinbase\\Wallet\\Client->getAndMap('/v2/accounts/99...', Array, 'toTransaction')
#6 /var/www/project/myproject/app/Helpers/CoinHelpers.php(152): Coinbase\\Wallet\\Client->getAccountTransaction(Object(Coinbase\\Wallet\\Resource\\Account), 'a835d342-b103-5...')

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
