### ISSUE TITLE
Unrecognized resource type: ethereum_classic_network and zcash_network

### ISSUE THREAD

**Issue by szwagros** [coinbase/coinbase-php#206]
Hi,

I'm trying to get information about transaction using following code:

```
        $transaction = new Transaction(
            null,
            $additionalData['transaction']['resource_path']
        );

        $this->client->refreshTransaction($transaction);
```
$additoonaData is data send to webhook notificaiton addres (https://developers.coinbase.com/api/v2#notifications)

But for ETC and ZEC exception is thrown with error "Unrecognized resource type: ethereum_classic_network" or zcash_network.

How can I fix this ?

**Comment by hungnm92** [comment]
The same issue #204 , please review issue for solution to fix.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
