### ISSUE TITLE
Question regarding Webhooks (event type and timeline)

### ISSUE THREAD

**Issue by Mecanik** [coinbase/coinbase-php#207]
I'm using webhooks to accept payments on a very big project, and whilst going through the documentation and writing code, I noticed something strange. 

Basically the timeline events are not documented as to what even type they are added. Sending tests to my webhook one by one from the coinbase commerce site, they make no sense once you get to "charge:failed".

From all your libraries created, whmcs, opencart, all of them; you are just using the timeline to process payments.

Question 1: Why ?
Question 2: Why are you ignoring the event type ?

And the most important question:

How should someone properly process payments, using the even type (charge:created, etc) or the timeline ?

I would really appreciate if you could clarify this for me, as I am about to integrate coinbase commerce into many big applications....

Thanks

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
