### ISSUE TITLE
How to get available balance for a fiat account

### ISSUE THREAD

**Issue by mfb** [coinbase/coinbase-php#209]
I need to automate withdrawals from a fiat (USD) account, but I'm not sure how to retrieve the _available_ balance from the Coinbase API.

I can only get the balance, which includes unavailable funds that cannot be withdrawn (e.g. due to pending deposit).

The available balance is visible in the Coinbase web UI, so should be retrievable somehow? :)

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
