### ISSUE TITLE
getorder() always errors 'Order not found with that id'

### ISSUE THREAD

**Issue by Taiiwo** [coinbase/coinbase-php#26]
For example:
    $coinbase = Coinbase::withApiKey($_API_KEY, $_API_SECRET);
    $buttoncode = $coinbase->createButton('name',0.001,'BTC')->button->code;
    $order = $coinbase->createOrderFromButtonCode($buttoncode);
    $id = $order->order->id;
    $order = $coinbase->getorder($id);

Returns:

Fatal error: Uncaught exception 'Coinbase_ApiException' with message 'Order not found with that id' in /path/to/Coinbase/Rpc.php:107 Stack trace: #0 /path/to/Coinbase/Coinbase.php(64): Coinbase_Rpc->request('GET', 'orders/HC3ETHKD', Array) #1 /path/to/Coinbase/Coinbase.php(333): Coinbase->get('orders/HC3ETHKD', Array) #2 /path/to/c.php(24): Coinbase->getOrder('HC3ETHKD') #3 {main} thrown in /path/to/Coinbase/Rpc.php on line 107 

UPDATE: This is returned when you check an order that has not had money send to it yet. After a while, the function completes with status 'expired'. I think this error should be handled within that API.

**Comment by aianus** [comment]
Please re-open if you're still experiencing this on v2 of the api / client.
