### ISSUE TITLE
Sandbox Api keys are not working

### ISSUE THREAD

**Issue by anistark** [coinbase/coinbase-php#42]
Hi,

For testing, I created a sandbox account and new API tokens. But, everytime I request anything using that, I get this:

Coinbase_ApiException
Status code 401

Please help.

**Comment by ShaiJames** [comment]
I get the same error

**Comment by rsmith87** [comment]
I ran into that issue because the API access was not enabled.  Once it was enabled it allowed me to use the API.

**Comment by gadsred** [comment]
i already enabled my api key but still got this error im using sandbox

**Comment by jorilallo** [comment]
Sandbox is a separated system with a different domain and this is why your keys aren't working (they are authenticated agaisn't production system). We plan to add sandbox support in the future.

**Comment by ShaiJames** [comment]
Is there anything we can change on our side? It's pretty hard to test using sandbox without actually being able to test using sandbox :) 

If not, what are our current options? Should we just plop some petty cash into a production account and test with that?

**Comment by jjmardlin** [comment]
On [this line of the PHP library](https://github.com/coinbase/coinbase-php/blob/master/lib/Coinbase/Coinbase.php#L5), change 
`https://api.coinbase.com/v1/` to `https://api.sandbox.coinbase.com/v1/`

That should do it.

**Comment by ShaiJames** [comment]
The only problem we saw with this change so far was that $button (s) are not getting set, with a returned error of "Invalid data-code attribute (1)". 

The coinbase team is apparently working on the issue and will update us when it's available.

**Comment by dmp1ce** [comment]
Both #46 and #44 pull requests add sandbox support.

**Comment by IndiesServices** [comment]
I have already changed all files define here https://github.com/coinbase/coinbase-magento/search?utf8=%E2%9C%93&q=coinbase.com. But still getting error :     Uncaught exception 'Coinbase_ApiException' with message 'Status code 401'

**Comment by aianus** [comment]
Please re-open if you are still having issues using the latest version of the PHP library on sandbox.
