### ISSUE TITLE
Documentation for get()

### ISSUE THREAD

**Issue by gerbz** [coinbase/coinbase-php#45]
Tiny issue, but I banged my head against the wall for hours...

In the documentation you show:
```
var_dump($coinbase->get('/account/balance'));
```

For get() to work, you need to leave off the initial slash:
```
var_dump($coinbase->get('account/balance'));
```

**Comment by aianus** [comment]
Hmm both should work, we ltrim the '/' off the provided path. Please re-open if you are still experiencing this issue on the latest version of the library.
