### ISSUE TITLE
try catch

### ISSUE THREAD

**Issue by gregtampa** [coinbase/coinbase-php#48]
try {
$coinbase = Coinbase::withApiKey($coinbaseAPIKey, $coinbaseAPISecret);
}

//catch exception
catch(Exception $e) {
  echo 'Message: ' .$e->getMessage();
}

above is an example of a try catch..
I noticed a lot of calls do not have try catch and will error our the website if =using the coinbase-php class.
I would like to request someone go in and use try catch to prevent fatal errors.

inside line 22 of Requestor.php

**Comment by aianus** [comment]
It would be up to the user of the library to catch these exceptions and handle them as he/she wishes. We have no way of knowing, as the authors of the library, how errors should be handled in each individual application.
