### ISSUE TITLE
Price can't be blank

### ISSUE THREAD

**Issue by saitho** [coinbase/coinbase-php#49]
Hi,
I'm having an issue with creating buttons... When I first tried it in April it worked...
Now I get the error "Price can't be blank" - even with the example (ApiKeyExample.php).

Kind regards
Mario

BTW, the response from the Server is:
array(2) { ["statusCode"]=> int(200) ["body"]=> string(515) "{"success":false,"errors":["Price can't be blank"],"button":{"code":"fd0f6d06b7e7b02cd9049ea9b79fd63b","type":"buy_now","subscription?":false,"repeat":null,"style":"buy_now_large","text":"Pay With Bitcoin","name":"Alpaca socks","description":"","custom":"","callback_url":null,"success_url":null,"cancel_url":null,"info_url":null,"auto_redirect":false,"auto_redirect_success":false,"auto_redirect_cancel":false,"price":null,"variable_price":false,"choose_price":false,"include_address":false,"include_email":false}}" }

**Comment by patrickdk77** [comment]
Looks like the code is just bad. It is sending url encoded params instead of the required json.

Edit lib/Coinbase/Rpc.php on line 17, and change http_build_query to json_encode

**Comment by aianus** [comment]
We support both json and url encoded POST bodies. Please re-open if you are still having issues with the latest version of the library.
