### ISSUE TITLE
api v2

### ISSUE THREAD

**Issue by gregtampa** [coinbase/coinbase-php#50]
v2 has a new auth must update it here, 
also consider passing which api to use in a config, along with sandbox/prod url endpoints.

**Comment by jorilallo** [comment]
We're working on a new version of the library which is targeted towards v2 authentication and endpoints. I'll keep this open until it is released

**Comment by shellprog** [comment]
Any update on this ?

**Comment by cihantas** [comment]
Is there an estimated release date?

**Comment by jorilallo** [comment]
Most likely next week

**Comment by adrianmacneil** [comment]
:boom:

**Comment by jorilallo** [comment]
@gregtampa @shellprog @cihantas Take a look at v2 :)

**Comment by shellprog** [comment]
Superb work , thanks alot for this release , i will test it this weekend and let u know if any issues .

**Comment by gregtampa** [comment]
congratz, ill test it for errors soon..

**Comment by cihantas** [comment]
You guys rock!
