### ISSUE TITLE
getExchangeRate

### ISSUE THREAD

**Issue by gregtampa** [coinbase/coinbase-php#51]
getExchangeRate currently is pulling 10000.00 in the sandbox
yet on coinbase it showing 1 BTC is 10100.00
http://prntscr.com/7qg591

Does it do this on non sandbox too? api not current with live time tracking of values?

**Comment by jorilallo** [comment]
API is live tracking correct values but the reason why these are different yields from the fact that we show buy price on the header and spot price in the exchange rates. If you want to quote Coinbase price, I suggest that you use the spot rate.

**Comment by gregtampa** [comment]
ended up calling buy and sell price function instead.
