### ISSUE TITLE
getSellPrice

### ISSUE THREAD

**Issue by gregtampa** [coinbase/coinbase-php#52]
https://api.coinbase.com/v1/prices/sell?qty=1
returns:
```
{"btc":{"amount":"1.00000000","currency":"BTC"},"subtotal":{"amount":"267.38","currency":"USD"},"fees":[{"coinbase":{"amount":"2.52","currency":"USD"}},{"bank":{"amount":"0.15","currency":"USD"}}],"total":{"amount":"264.71","currency":"USD"},"amount":"264.71","currency":"USD"}
```

but:
```
    public function getSellPrice($qty=1)
    {
        return $this->get("prices/sell", array( "qty" => $qty ))->amount;
    }


function getSellPrice(){
	global $coinbase;
	return $coinbase->getSellPrice();
}
```
returns: 
string(7) "9801.00"

**Comment by jorilallo** [comment]
Are you making calls against Sandbox? it has different rates. Closing this as I don't think this is an actual issue in the library

**Comment by gregtampa** [comment]
Please reopen I tested on both.. same results.
https://api.sandbox.coinbase.com/v1/prices/sell?qty=1
https://api.coinbase.com/v1/prices/sell?qty=1

both return same json outputs, however they are not collected correctly with the function in the coinbase-php as it only yields 1 value.
