### ISSUE TITLE
Can't Authenticate Using Built-In Functions

### ISSUE THREAD

**Issue by utdrmac** [coinbase/coinbase-php#55]
What am I doing wrong? I'm following the documentation. I'm providing the correct headers but keeps failing.

```
$configuration = Configuration::apiKey($apiKey, $apiSecret);
$authentication = $configuration->getAuthentication();

$headers = $auth->getRequestHeaders('GET', '/v2/prices/buy?currency=USD', '');
$headers['CB-VERSION'] = Configuration::DEFAULT_API_VERSION;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.coinbase.com/v2/prices/buy?currency=USD");
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($ch, CURLOPT_CAINFO, __DIR__ . "/vendor/coinbase/coinbase/etc/ca-coinbase.crt");

$response = curl_exec($ch);

var_dump($response);

curl_close($ch);
```

The result, with the headers (replaced a fake access key for posting):
```
array(4) {
  ["CB-ACCESS-KEY"]=>
  string(16) "KJSDKFJLDSFIJ"
  ["CB-ACCESS-SIGN"]=>
  string(64) "ceb8b94e246b894a9636808640bdd9c2fab3c1b9d16372aff2b184cbbe76bd95"
  ["CB-ACCESS-TIMESTAMP"]=>
  int(1440100264)
  ["CB-VERSION"]=>
  string(10) "2015-07-07"
}
string(240) "{"errors":[{"id":"invalid_token","message":"The access token is invalid"}],"warnings":[{"id":"missing_version","message":"Please supply API version (YYYY-MM-DD) as CB-VERSION header","url":"https://developers.coinbase.com/api#versioning"}]}"
```

So, my headers look correct according to the docs. I'm providing CB-VERSION. I don't get it.

**Comment by utdrmac** [comment]
Sigh. This needs better documentation. Maybe some real examples? Why would getRequestHeaders() not return EXACTLY what is required? This worked:

```
$headers = $auth->getRequestHeaders('GET', '/v2/prices/buy?currency=USD', '');
$headers['CB-VERSION'] = Configuration::DEFAULT_API_VERSION;

$newHeaders = array();
foreach($headers as $h => $v)
{
	$newHeaders[] = "$h: $v";
}
curl_setopt($ch, CURLOPT_HTTPHEADER, $newHeaders);
```

**Comment by aianus** [comment]
Sorry you had difficulty. We don't have documentation for those methods because they are not meant to be called by users of the library. Was there a specific reason you needed to use curl instead of the bundled http client?

**Comment by utdrmac** [comment]
Because on the Google App engine, the PHP supplied environment has SSL verification and Google does NOT let you override the CA_CERT parameters. You have to use native curl functionality to add in coinbase's SSL stuff.

**Comment by aianus** [comment]
Ugh Google App Engine is so obnoxious. We had a customer with a similar issue using the Java library.

In any case, glad you got it working.
