### ISSUE TITLE
Unrecognized resource type: bitcoin_network

### ISSUE THREAD

**Issue by jorilallo** [coinbase/coinbase-php#56]
Mapper fails when calling `$client->getAccountTransactions($account)` and the returned transaction has originated from bitcoin network (no way to map into an object). Example transaction:

```json
{
  "id": "eb6620e4-995d-5542-adda-dcaf3537705d",
  "type": "send",
  ...
  "from": {
    "resource": "bitcoin_network"
  }
}
```

**Comment by corper** [comment]
This is a critical bug. Hope you fix it soon.
