### ISSUE TITLE
Unhandled exception in createAccountTransaction() if bad tx data is given

### ISSUE THREAD

**Issue by Cb-James** [coinbase/coinbase-php#76]
If createAccountTransaction is called with a transaction with an invalid address, or an amount is given that can't be sent, the following error is thrown:

> Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 422'

Code to reproduce:

```
<?php
  require_once('vendor/autoload.php');

  use Coinbase\Wallet\Client;
  use Coinbase\Wallet\Configuration;
  use Coinbase\Wallet\Resource\Transaction;
  use Coinbase\Wallet\Value\Money;
  use Coinbase\Wallet\Enum\CurrencyCode;
  use Coinbase\Wallet\Value\Fee;
  use Coinbase\Wallet\Enum\Param;
  use Coinbase\Wallet\Resource\Address;

  $apiKey="apikey";
  $apiSecret="apisecret";

  # a bad address and/or an invalid amount will cause the issue
  $address = 'bad_address';
  $btcvalue = 'amount_greater_than_wallet_balance';

  $configuration=Configuration::apiKey($apiKey, $apiSecret);
  $client=Client::create($configuration);
  $account=$client -> getPrimaryAccount();
  $transaction = Transaction::send([
    'toBitcoinAddress' => $address,
    'amount' => new Money($btcvalue, CurrencyCode::BTC),
    'description' => "bad transaction"
  ]);
  $client->createAccountTransaction($account, $transaction);
  echo $transaction->getId();
?>

```

More discussion here:
https://community.coinbase.com/t/getting-status-result-php/8427/4
https://community.coinbase.com/t/error-guzzlehttp/7577/3

**Comment by aianus** [comment]
I think this is the expected behavior when trying to create a transaction with bad arguments.

We can link people to http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions to see how to handle exceptions in their applications. Eg.

```php
try {
    $client->createAccountTransaction($account, $transaction);
} catch (ClientException $e) {
    echo $e->getRequest();
    echo $e->getResponse();
}
```

**Comment by Cb-James** [comment]
@aianus more trouble with this here #77 -- exception handling from this angle doesn't seem to work, or we're not doing it right.
