### ISSUE TITLE
Unhandled exception on createAccountBuy

### ISSUE THREAD

**Issue by JamesNock** [coinbase/coinbase-php#77]
Hi guys, I can't seem to find any way of dealing with the Fatal Exception that I receive when using the following:

`
$client = Client::create($configuration);

$account = $client->getPrimaryAccount();

    $buy = new Buy([
        'bitcoinAmount' => $tokens['amount']
        ]);

    try {

        $client->createAccountBuy($account, $buy);

    } catch (ClientException $e) {
        
        var_dump($e->getResponse()); die;

    }

}`

Which works fine if the user has sufficient funds in their account to buy the btc with. However, if an error response is sent back instead, I get a message like:

Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.sandbox.coinbase.com/v2/accounts/555d9af2-d78b-5ce5-9a1f-031f394a3a51/buys` resulted in a `422 Unprocessable Entity` response:
{"errors":[{"id":"validation_error","message":"This would exceed your bank purchase limit of $1,000.00 per day. Please w (truncated...)
' in /home/coinbase/httpdocs/include/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /home/coinbase/httpdocs/include/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/coinbase/httpdocs/include/vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/coinbase/httpdocs/include/vendor/guzzlehttp/promises/src/Promise.php(154): GuzzleHttp\Promise\Promise::callHandler(1, Object(Gu in /home/

I asked how I could resolve this on the coinbase forum and was told to log an issue here, so I have.

Thanks in advance!

**Comment by aianus** [comment]
Are you catching the correct ClientException?

Try adding

```php
use GuzzleHttp\Exception\ClientException;
```

at the top of your file.

**Comment by JamesNock** [comment]
Thanks for the reply. I have both of these at the top of my file:

use Coinbase\Wallet\Exception;
use GuzzleHttp\Exception\ClientException;

Do you have any more ideas?

**Comment by aianus** [comment]
Have you tried catching `\Exception` instead? It might be a namespace resolution issue, in which case `use \GuzzleHttp\Exception\ClientException;` (with the leading backslash) might fix it.

In any case, it doesn't appear to be an issue with the library so I'm going to close the issue.

**Comment by JamesNock** [comment]
I did try it with \Exception. I stopped using the library in the end as I couldn't get it to do what I needed. Thanks for your help.
