### ISSUE TITLE
worst details ever on github

### ISSUE THREAD

**Issue by Sarfroz** [coinbase/coinbase-php#78]
i do not understand why you guys not give proper information. if you update composer it will give lib of api v1 but of not v2. Please check details and give proper documentation before release.

**Comment by mardlin** [comment]
Thanks for the feedback. Please take a respectful tone. You will find that it is more effective, both in this repository and elsewhere on GitHub. 

Can you please clarify the issue you are experiencing? What do you mean by

> if you update composer it will give lib of api v1 but of not v2
?

What steps did you take before running into the problem? That information will help us to reproduce and address the issue.

**Comment by adnandogar** [comment]
@Sarfroz having no understanding about code and before reading all docs, does't mean by repository have issues.  

composer v1 and v2 will be some different issue, put your error log here so that issue can be identified.

**Comment by Sarfroz** [comment]
Thanks  alot for the reply but after spending 3 hours on this small piece
of code i was able to use v1 api codes .
