### ISSUE TITLE
Client::createAccountAddress void

### ISSUE THREAD

**Issue by abgit** [coinbase/coinbase-php#82]
Hi all,

After testing some api i found, on your docs, that we can create an account address.
```php
use Coinbase\Wallet\Resource\Address;

$address = new Address([
    'name' => 'New Address'
]);
$client->createAccountAddress($account, $address);
```
the problem is that `createAccountAddress()` don't return anything. So, we don't have access to newly generated `ResourceCollection|Address`.

Maybe you should change [$client->createAccountAddress](https://github.com/coinbase/coinbase-php/blob/master/src/Client.php#L298) from:

```php
     $this->postAndMap(..);
}
```
to

```php
     return $this->postAndMap(..);
}
```

what do you think?

best
FA

**Comment by aianus** [comment]
The created address resource will be accessible via the $address variable you passed in.

eg.

```
$address = new Address([
    'name' => 'New Address'
]);
$client->createAccountAddress($account, $address);
echo $address->getAddress();
```

This is consistent with the other methods in the library such as `createCheckout` and `createOrder`.
