### ISSUE TITLE
Error when sending funds

### ISSUE THREAD

**Issue by izacGaldino** [coinbase/coinbase-php#85]
Hi guys , I'm having an error when sending funds , the code I am using is this:

```
$transacao = Transaction::send();
    
    $transacao->setToBitcoinAddress($endereco);
    $transacao->setAmount(new Money($montante, CurrencyCode::BTC));
    $transacao->setDescription($description);

 try {
        $client->createAccountTransaction($conta, $transacao);
    } catch (ClientException $e) {
        $e->getRequest();
        $e->getRespose();
    }
```

When I open the page I get this error:

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid resource type: boolean' in /home/u951323236/public_html/php/vendor/guzzlehttp/psr7/src/functions.php:113 Stack trace: #0 /home/u951323236/public_html/php/vendor/guzzlehttp/guzzle/src/Client.php(360): GuzzleHttp\Psr7\stream_for(false) #1 /home/u951323236/public_html/php/vendor/guzzlehttp/guzzle/src/Client.php(264): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array) #2 /home/u951323236/public_html/php/vendor/guzzlehttp/guzzle/src/Client.php(98): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #3 /home/u951323236/public_html/php/vendor/guzzlehttp/guzzle/src/Client.php(104): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array) #4 /home/u951323236/public_html/php/vendor/coinbase/coinbase/src/HttpClient.php(135): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array) #5 /home/u951323236/public_html/php/vendor/coinbase/coinbase/src/HttpClient.php(121): Coinbase\Wallet\HttpClient->send in /home/u951323236/public_html/php/vendor/guzzlehttp/psr7/src/functions.php on line 113

Sorry for my english :smile:

**Comment by Cb-James** [comment]
Very likely related to #76 and #77.

**Comment by izacGaldino** [comment]
Thanks for the reply , I discovered the errors. The first was that he was trying to send money for an own address account , the other is the amount that was getting in scientific notation.
