### ISSUE TITLE
Unrecognized resource type: application

### ISSUE THREAD

**Issue by antho281** [coinbase/coinbase-php#86]
Hi all!

I'm getting this error when I'm running 
`$account = $client->getAccount($wallet);
 $address = $client->getAccountAddress($account,$address_id);
 $transactionaddr = $client->getAddressTransactions($address);`

ERROR : `Unrecognized resource type: application`

I have tested getApplication() and had no luck so far.

It looks like the API can't check the transactions from Coinbase mobile Apps. 
Am I doing something wrong?

Thanks in advance for your help!

**Comment by aianus** [comment]
Thanks for bringing this bug to our attention. It should be fixed as of version 2.4.0 on Github and Packagist
