### ISSUE TITLE
Coinbase createAccountAddress() returns null, address will be generated

### ISSUE THREAD

**Issue by Pekinese** [coinbase/coinbase-php#90]
When using this code it shows null all the time, but a new address is generated. What's wrong with coinbase API?

    $configuration = Configuration::apiKey("xy", "xy");
        $client = Client::create($configuration);

        $account = $client->getPrimaryAccount();
        $address = new Address([
            'name' => null
        ]);

       $return =  $client->createAccountAddress($account, $address);

       die((var_dump($return));

**Comment by aianus** [comment]
The return value will be present in the $address variable, it is not returned from the function.
