### ISSUE TITLE
Need a way to lookup the old V1 API Coinbase order using CoinbaseV2 API

### ISSUE THREAD

**Issue by kafuwale** [coinbase/coinbase-php#91]
Currently we are using Coinbase v1 APIs for our merchant solution and have following information in callback url 

{"order":{"id":"W28I95JR","uuid":"f690517b-d19d-5b91-af9a-7cfe9891501e","resource_path":"/v2/orders/f690517b-d19d-5b91-af9a-7cfe9891501e","metadata":null,"created_at":"2016-06-05T01:01:53-07:00","status":"completed","event":{"type":"completed"}........

We as a merchant store, id (OIrderNumber) (eg. W28I95JR , in coinbase V2 API its refer as Code field) in our system and order can be looked by by V1 API using  orders/ by passing id (W28I95JR) to get all relevant information. 

Now we are planning to use Coinbase V2 api and we have only information stored is coinbase order Number( id field in above example i.e W28I95JR) ,and we want to look up an order using this Order Number,and we are not finding any way to lookup order using V2 API.

We found V2 API (/v2/orders/)  to lookup the order but it need the uuid field to be passed and not worked by passing the Order Number.

Can you please suggest how to lookup the old V1 orders using V2 Coinbase API using Order Number (id field) ?

**Comment by aianus** [comment]
I can forward this issue to our API team to see what they have to say but as a workaround you can run a one-time script against your db that looks up orders via API v1 and saves the v2 uuid (which is returned as part of the API v1 response).

**Comment by kafuwale** [comment]
Thanks Aianus , will continue with the this workaround solution and looking forward to have same feature in next API version.
