### ISSUE TITLE
Intermittent response `403 Forbidden` ,while calling V2 getOrder functions

### ISSUE THREAD

**Issue by kafuwale** [coinbase/coinbase-php#92]
Hi,

We are using coinbase V2 API to look up the orders and we are frequently getting `403 Forbidden` response in exception while lookup .

Actual error message 

Client error: `GET https://api.coinbase.com/v2/orders/b028335c-5d7e-5f7b-ba6c-87ca2e081122` resulted in a `403 Forbidden` response ....etc

This is occurring too frequently for many of the orders.  

Can you please help us for the same, what would be the root cause of this?

**Comment by aianus** [comment]
What is the full body of the 403 response? It is possible you are being rate-limited for making too many requests too fast.

**Comment by kafuwale** [comment]
Hi Aianus ..

Here is the full body response from the V2 API

Client error: `GET https://api.coinbase.com/v2/orders/dc25a7d1-7a31-5ebb-9d57-7a791be2f0ec` resulted in a `403 Forbidden` response:
<!DOCTYPE html>

<!--[if IE 7]>    <html class (truncated...) 

Also, same API key is working from one server but given  giving error from another..:(

Also,not think it's being rate-limited as coinbase default rate limit is 10,000 requests per hour and we are not reaching up to that request per hour.

Please suggest.

**Comment by kafuwale** [comment]
Any update on same?

**Comment by aianus** [comment]
Can I see the full text of the response please?

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen with the requested information. Thanks!
