### ISSUE TITLE
Which algorithm used by coinbase..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [coinbase/coinbase-php#93]
May I know which algorithm used by coinbase..? Using createAccountAddress() function we generate account address right.?

**Comment by aianus** [comment]
Yes, that's correct. Not sure what you mean by what algorithm we use.

**Comment by Lalitpatadiya12** [comment]
I mean when we call createAccountAddress() it return one address so it's a random generated string or u guys are using any algorithm for that.?

I hope now you got it what exactly I am mean.

**Comment by aianus** [comment]
Yes, addresses are generated randomly.

**Comment by aianus** [comment]
You can find the technical details on how the visible address is derived from the ECDSA keypair here: https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses
