### ISSUE TITLE
Is their any minimum requirement of php..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [coinbase/coinbase-php#95]
Hello Alex,

I have install bitcoin in my code and it'll installed successfully but when I fetch price of current bitcoin it'll give me error.

Call to undefined function GuzzleHttp\Handler\curl_reset() in /home1/ab95976/public_html/qa/digypay/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

Can you just let me know why it'll give error like above...?

**Comment by StefanYohansson** [comment]
@Lalitpatadiya12 can you provide your PHP version?

**Comment by Lalitpatadiya12** [comment]
PHP Version 5.4.45

**Comment by aianus** [comment]
@StefanYohansson is correct, it appears your PHP version is too old.

Similar issue: https://github.com/Codeception/Codeception/issues/2124

**Comment by Lalitpatadiya12** [comment]
Ok, but now I have upgrade my php version to  5.6.19 and Found error when I integrating sandbox in my code like $configuration->setApiUrl(Configuration::SANDBOX_API_URL); then it'll give me error like bellow 

Uncaught exception 'GuzzleHttp\Exception\ServerException' with message ' in D:\wamp\www\open_digy-pay\trunk\vendor\coinbase\coinbase\src\Exception\HttpException.php on line 37

**Comment by StefanYohansson** [comment]
This is my coinbase singleton class. See if you are doing everything like this.

```php
<?php

namespace BrasilMiner;

use Coinbase\Wallet\Client as CoinbaseClient;
use Coinbase\Wallet\Configuration;

class Coinbase
{
    protected $coinbase = null;

    public function __construct()
    {
        if ($this->coinbase) {
          return $this->coinbase;
        }

        $configuration = Configuration::apiKey(config('coinbase.apiKey'),
            config('coinbase.apiSecret'));

        if (config('coinbase.sandbox')) {
            $configuration->setApiUrl(Configuration::SANDBOX_API_URL);
        }
        $this->coinbase = $client = CoinbaseClient::create($configuration);

        return $client;
    }

    public function action($action, $args = array()) {
        return call_user_func_array([$this->coinbase, $action], $args);
    }
}
```

you can ignore action function since this is just for use this way: `$this->coinbase->action('deleteAccount', [$account])`
but you can use:
`$this->coinbase->deleteAccount($account)`

**Comment by aianus** [comment]
@Lalitpatadiya12 

This is likely our sandbox environment being flaky, not a problem with your code. It is better to test in production with small amounts of bitcoin.

**Comment by Lalitpatadiya12** [comment]
@aianus  So can you just let me know any solution for the same because I want to use your api just because my project having same requirements.

**Comment by aianus** [comment]
Can you not use the production site (without `$configuration->setApiUrl(Configuration::SANDBOX_API_URL);`)?
