### ISSUE TITLE
$transactionId as return when createAccountTransaction is called

### ISSUE THREAD

**Issue by rodriguezVR** [coinbase/coinbase-php#96]
Hi,

In order to direct check if transaction was successfully created or is completed later, I would like to get the $transactionId at same time when transaction is created. 

Is this requested return already implemented?

$transaction = Transaction::send([
    'toBitcoinAddress' => 'ADDRESS',
    'amount'           => new Money(5, CurrencyCode::USD),
    'description'      => 'Your first bitcoin!',
    'fee'              => '0.0001' // only required for transactions under BTC0.0001
]);

$client->createAccountTransaction($account, $transaction);

Thanks!

**Comment by PriyanshDwivedi** [comment]
I believe the original `$transaction` object will have the transaction id after `createAccountTransaction()` is called. You can try accessing it like `$transaction->getNetwork()-> getHash()`
