### ISSUE TITLE
Sandbox error..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [coinbase/coinbase-php#97]
When I am integrating coinbase, I got error like below.
![localhost open_digy pay trunk public admin content buy_sell_transaction](https://cloud.githubusercontent.com/assets/20555552/17730979/d75a9108-6488-11e6-986f-636b64460c32.png)

Sandbox is working or not with coinbase api..?

**Comment by aianus** [comment]
The sandbox is flaky right now, I would suggest using production.
