### ISSUE TITLE
When I request it'll give error..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [coinbase/coinbase-php#99]
Why I am facing this type of error when I sent new transaction request..?

A PHP Error was encountered

Severity: 4096

Message: Argument 1 passed to Coinbase\Wallet\Client::createAccountTransaction() must be an instance of Coinbase\Wallet\Resource\Account, instance of Coinbase\Wallet\Resource\Transaction given, called in D:\wamp\www\open_digy-pay\trunk\application\modules\web_service\controllers\web_service.php on line 144 and defined

Filename: src/Client.php

Line Number: 361

**Comment by aianus** [comment]
You need to include an account object as the first parameter, as shown in the README

```
$client->createAccountTransaction($account, $transaction);
```
